# Generated by Django 3.1.7 on 2021-07-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210623_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=300)),
                ('receiver', models.CharField(max_length=300)),
                ('funds', models.IntegerField(default=0)),
            ],
        ),
    ]
